### ISSUE TITLE
Why is that

### ISSUE THREAD

**Issue by Demolemon11** [project-robius/robrix#166]
```
    RoomsList = {{RoomsList}} {
        width: Fill, height: Fill
        flow: Up

        list = <PortalList> {
            keep_invisible: false
            width: Fill, height: Fill
            flow: Down, spacing: 0.0

            room_preview = <RoomPreview> {}
            empty = <Empty> {}
            room_status_label = <StatusLabel> {}
            bottom_filler = <View> {
                width: Fill,
                height: 100.0,
            }
        }
    }
```
### In the `rooms_list.rs`, once you change the `height`  under `RoomsList` `Fill` to `Fit`, Robrix will run with a black screen, and Large amount of memory consumption.

**Comment by Demolemon11** [comment]
I have a type `PeopleList`, I mostly guess the reson only one of the both (`RoomsList` & `PeopleList`) can correctly display is both them two want to FILL the siderbar
So I change both them `Fill` to `Fit`, but instead of working properly, it's become more abnormal.

**Comment by Demolemon11** [comment]
This issue is for pr #154

**Comment by kevinaboos** [comment]
> In the `rooms_list.rs`, once you change the `height` under `RoomsList` `Fill` to `Fit`, Robrix will run with a black screen, and Large amount of memory consumption.

Not sure, that's a Makepad thing and doesn't have anything to do with Robrix specifically. I'd say it's likely because with that change, you'd be trying to have a view with a `Fill` height inside of a view with a `Fit` height, which logically doesn't make any sense.  "Fit" is telling the layout system that you want the view to only take up as much height as is needs, while "fill" means that it should take up as much vertical space as is available. So combining those two in that way wouldn't make sense anyway. Were you trying to do that for some particular reason?

**Comment by kevinaboos** [comment]
i've recently rewritten the entire backend and am about to change the way that rooms are stored and filtered/sorted in the rooms list, so a lot of this code is undergoing major changes right now. 
I recommend that you wait for those changes to pan out before trying to make other major changes to the rooms list.

**Comment by kevinaboos** [comment]
the changes are in, but the frontend itself (the RoomsList and RoomPreviewEntry) remains the same, for now.
