### ISSUE TITLE
Add a "Jump to Bottom" button 

### ISSUE THREAD

**Issue by kevinaboos** [project-robius/robrix#85]
I think the best way to display this is as a simple `IconButton` that floats above the Timeline view -- in Makepad terms, this is a simple overlay that would be invisible by default, and only set to visible when the user scrolls up to a position that is sufficiently far away from the latest message at the bottom.

Upon being clicked, we should perform the nice scrolling action by calling Makepad's [`PortalList::smooth_scroll_to_end()` function](https://github.com/makepad/makepad/blob/057ba860504c011bc45c672e2337b87a3696c166/widgets/src/portal_list.rs#L886)

Here's how Element displays this:
<img width="445" alt="image" src="https://github.com/user-attachments/assets/23965b73-62cb-43ab-a338-b8e324b3032b">

Here's how Signal displays this button, which is identical to Element:
<img width="744" alt="image" src="https://github.com/user-attachments/assets/37fe54f0-9e51-436d-b5d1-b4f2016b04e3">

Here's how Discord displays this, as a banner atop the message input box:
<img width="827" alt="image" src="https://github.com/user-attachments/assets/9b868f29-c3d9-4317-87f2-483f88e04061">

**Comment by smarizvi110** [comment]
Hello! New to Rust and OSS here. I'd like to help with this issue. Would appreciate any tips and directions to get started! Thanks!

**Comment by smarizvi110** [comment]
I encountered a few issues while implementing the button in Makepad.

1. I created an SVG with a downward arrow inside a circle, similar to ICO_ADD. However, when using IconButton, only the arrow displayed. It seems IconButton only processes `<path>` elements and ignores `<circle>` elements, and ICO_ADD seems to combine its plus sign and circle into a single `<path>`.

2. I tried using `draw_bg` to draw a circle behind the arrow instead, but I couldn't center it properly or prevent it from being clipped when larger than the button's bounding box.

3. I added the button to the `Timeline` definition instead of above the `message_input` `<View>` to ensure it floats without a rectangular background that obstructs the timeline, but it was placed at the top right corner. How can I position it from the bottom right corner without using offsets, which seem less clean and might not adapt to different screen sizes?

Any help would be appreciated!

**Comment by kevinaboos** [comment]
Hi @smarizvi110, apologies that I missed your replies until today. Thanks so much for looking into this!

I'm not a true expert in Makepad but I do have some experience, and more importantly, lines of contact with Makepad experts. I'll take a look at your PR later today and respond there.

Makepad's SVG support is indeed incomplete and only supports `<path>` elements; that is a known issue but is being addressed currently (AFAIK).

**Comment by kevinaboos** [comment]
@smarizvi110 i pushed some changes to your PR #91 and left some comments. Thanks a lot for getting this started!

**Comment by smarizvi110** [comment]
@kevinaboos Hey, thanks for the response! Glad to hear the SVG support is being worked on. I'll take a look at your changes and comments! Thank you!
